
import { UserProfile, DailyMode, Toast } from '../../types/types';
import { DAILY_TARGETS, MILESTONE_REWARDS } from '../../types/constants';
import { sendNotification } from '../../utils/notifications';
import { BadgeDefinition } from '../../types/badgeTypes';

interface MidnightResult {
    newUser: UserProfile;
    toastMessage: string;
    toastType: Toast['type'];
    newBadge?: BadgeDefinition; // 👈 Badge generated by system
}

export const calculateMidnightUpdates = (user: UserProfile, debugDate: string | null | undefined): MidnightResult => {
    const target = user.dailyTarget;
    const earned = user.dailyXP;
    const targetMet = earned >= target; // Did they hit the daily goal?
    
    // Use debug date if available, otherwise real time
    const now = debugDate ? new Date(debugDate) : new Date();
    
    // Check for month change
    let newBadge: BadgeDefinition | undefined = undefined;
    let badgeToast = "";

    // Recalculate everything else
    let newStreak = user.streak;
    let newGold = user.gold;
    let newShields = { ...user.shields };
    let newConsecutiveShields = user.consecutiveShields || 0;
    let newShieldsUsedMetric = user.metrics.shieldsUsed;
    let toastMessage = '';
    let toastType: Toast['type'] = 'info';
    
    // 🗓️ Check if current day was a scheduled rest day
    const dayToCheck = user.lastProcessedDate.split('T')[0];
    const isRestDay = user.restDays && user.restDays.includes(dayToCheck);

    if (targetMet) {
        newStreak++;
        newConsecutiveShields = 0; 
        
        const salary = user.currentMode === DailyMode.HARD ? 200 : user.currentMode === DailyMode.NORMAL ? 100 : 50;
        newGold += salary;
        
        toastMessage = `🌅 New Day! Streak ${newStreak} | +${salary}G`;
        toastType = 'success';

        const bonus = MILESTONE_REWARDS[newStreak];
        if (bonus) {
            newGold += bonus;
            toastMessage = `🏅 Milestone: ${newStreak} Days! +${bonus}G`;
            toastType = 'level-up';
            if (user.preferences.deviceNotificationsEnabled) {
                sendNotification('🏅 Milestone Reached!', `You hit a ${newStreak} day streak! Bonus ${bonus}G awarded.`);
            }
        } else if (user.preferences.deviceNotificationsEnabled) {
            sendNotification('🌅 Protocol Reset', `New day initiated. Streak: ${newStreak}.`);
        }
    } 
    else if (isRestDay) {
        // 🧘 REST DAY PROTECTION
        toastMessage = `🧘 Rest Day Active. Streak Preserved at ${newStreak}.`;
        toastType = 'info';
        newConsecutiveShields = 0; // Reset count since it wasn't a failure
        if (user.preferences.deviceNotificationsEnabled) {
            sendNotification('🧘 Rest Day Protocol', `Protocol paused. Streak preserved at ${newStreak}.`);
        }
    }
    else {
        const currentMode = user.currentMode;
        const hasShield = newShields[currentMode] > 0;
        const canUseShield = newConsecutiveShields < 3; 

        if (hasShield && canUseShield) {
            newShields[currentMode]--;
            newConsecutiveShields++;
            newShieldsUsedMetric++;
            toastMessage = `🛡️ Streak Saved by ${currentMode.toUpperCase()} Shield (${newShields[currentMode]} Remaining)`;
            toastType = 'info';
            if (user.preferences.deviceNotificationsEnabled) {
                sendNotification('🛡️ Shield Deployed', `Your streak was saved. ${newShields[currentMode]} ${currentMode} shields remaining.`);
            }
        } else {
            if (hasShield && !canUseShield) {
                toastMessage = `🛡️ Shield Limit Exceeded! Streak Shattered.`;
            } else {
                toastMessage = `☠️ Target Missed. Streak Lost.`;
            }
            newStreak = 0;
            newConsecutiveShields = 0;
            toastType = 'error';
            if (user.preferences.deviceNotificationsEnabled) {
                sendNotification('☠️ Streak Lost', 'Protocol failed. System reset to Day 0.');
            }
        }
    }

    const nextMode = user.pendingMode;
    const nextTarget = DAILY_TARGETS[nextMode];

    const newUser: UserProfile = {
        ...user,
        streak: newStreak,
        gold: newGold,
        shields: newShields,
        consecutiveShields: newConsecutiveShields,
        dailyXP: 0, 
        dailyTarget: nextTarget, 
        currentMode: nextMode, 
        lastProcessedDate: now.toISOString(),
        lastOnline: now.toISOString(),
        metrics: {
            ...user.metrics,
            shieldsUsed: newShieldsUsedMetric,
            highestStreak: Math.max(user.metrics.highestStreak, newStreak)
        }
    };

    return { newUser, toastMessage, toastType, newBadge };
};
